/**
 * Type Definitions for NPC Advisor System
 *
 * This module defines all types related to the NPC Advisor System,
 * which provides context-aware recommendations to guide player decisions.
 *
 * @module AdvisorRecommendation
 */

import type { StoryGameState, NPCState, StoryAction } from '../../game-logic/StoryEngineAdapter';

// ============================================
// RECOMMENDATION TYPES
// ============================================

/**
 * Priority levels for recommendations
 * Determines visual presentation and urgency
 */
export type RecommendationPriority = 'critical' | 'high' | 'medium' | 'low';

/**
 * Categories of recommendations
 * Helps player understand the nature of the advice
 */
export type RecommendationCategory = 'opportunity' | 'threat' | 'efficiency' | 'strategy';

/**
 * Core recommendation structure
 * Generated by NPCs when analyzing game state
 */
export interface AdvisorRecommendation {
  // ========== Identity ==========
  /**
   * Unique identifier for this recommendation
   * Format: "npcId_category_timestamp" e.g. "marina_opportunity_1641234567"
   */
  id: string;

  /**
   * ID of NPC who generated this recommendation
   * e.g. "marina", "alexei", "igor", "katja", "direktor"
   */
  npcId: string;

  // ========== Priority & Category ==========
  /**
   * How urgent this recommendation is
   * Determines visual styling and sorting order
   * - critical: Red, pulsing, requires immediate attention
   * - high: Yellow/orange, steady glow
   * - medium: Green, subtle highlight
   * - low: Gray, normal styling
   */
  priority: RecommendationPriority;

  /**
   * Type of recommendation
   * - opportunity: Favorable circumstance to exploit
   * - threat: Danger or problem requiring attention
   * - efficiency: Optimization suggestion
   * - strategy: Long-term planning advice
   */
  category: RecommendationCategory;

  // ========== Content ==========
  /**
   * Player-facing message (German)
   * Short, actionable statement from NPC perspective
   * Examples:
   * - "Der Nordmark-Blackout ist unsere Chance. Schlage JETZT zu!"
   * - "Risiko bei 75%. Empfehle sofortige Sicherheitsmaßnahmen!"
   */
  message: string;

  /**
   * Detailed reasoning behind recommendation (German)
   * Educational explanation of why this matters
   * Shown in expandable section for transparency
   * Examples:
   * - "Crisis events create emotional vulnerability. Strike while public is confused."
   * - "Risk threshold critical. Detection likely in 3 phases."
   */
  reasoning: string;

  // ========== Actions ==========
  /**
   * Array of action IDs recommended by NPC
   * These actions will be highlighted in ActionPanel
   * Can be empty if recommendation is informational only
   */
  suggestedActions: string[];

  // ========== Context ==========
  /**
   * Phase number when recommendation was generated
   * Used for tracking and expiration
   */
  phase: number;

  /**
   * Optional expiration phase
   * If set, recommendation is invalid after this phase
   * Used for time-sensitive opportunities (world events, etc.)
   */
  expiresPhase?: number;

  // ========== Metadata ==========
  /**
   * NPC's confidence in this recommendation (0-1)
   * Affects dialogue tone and may be displayed to player
   * - 1.0: "Definitely do this"
   * - 0.7: "I strongly suggest"
   * - 0.5: "Consider this option"
   * - 0.3: "Might be worth trying"
   */
  confidence?: number;

  /**
   * IDs of other recommendations this conflicts with
   * Used for detecting NPC disagreements
   * Example: Marina suggests aggressive expansion, Igor warns about budget
   */
  conflictsWith?: string[];

  /**
   * Optional tone modifier for dialogue
   * Affects how message is presented
   */
  tone?: 'urgent' | 'cautious' | 'enthusiastic' | 'concerned' | 'neutral';
}

// ============================================
// ANALYSIS CONTEXT
// ============================================

/**
 * Complete context provided to NPCs for analysis
 * Contains all information needed to generate recommendations
 */
export interface NPCAnalysisContext {
  // ========== Current State ==========
  /**
   * Full game state snapshot
   */
  gameState: StoryGameStateSnapshot;

  /**
   * NPC performing the analysis
   * Used to access personality, relationship level, etc.
   */
  npc: NPCState;

  // ========== Historical Data ==========
  /**
   * Record of all actions taken by player
   * Used for pattern analysis and trend detection
   */
  actionHistory: ActionRecord[];

  /**
   * Historical metrics data
   * Used for calculating trends (reach growth, risk increase, etc.)
   */
  metricsHistory: MetricsHistory;

  // ========== Relationships ==========
  /**
   * Other NPCs in the game
   * Used for detecting conflicts and coordinating advice
   */
  otherNPCs: NPCState[];

  /**
   * Player's relationship level with this NPC (0-3)
   * Affects tone and depth of recommendations
   */
  playerRelationship: number;
}

/**
 * Snapshot of game state for analysis
 * Simplified version focusing on data NPCs need
 */
export interface StoryGameStateSnapshot {
  // Core State
  storyPhase: {
    phaseNumber: number;
    phaseName: string;
    year: number;
    month: number;
  };

  // Resources
  resources: {
    budget: number;
    maxBudget: number;
    capacity: number;
    maxCapacity: number;
    risk: number;
    attention: number;
    moralWeight: number;
  };

  // NPCs
  npcs: NPCState[];

  // Actions
  availableActions: StoryAction[];
  completedActions: string[]; // Action IDs

  // Events
  newsEvents: any[]; // NewsEvent type
  worldEvents: WorldEventSnapshot[];

  // Objectives
  objectives: ObjectiveSnapshot[];

  // Actors (if relevant for NPC analysis)
  actors?: ActorSnapshot[];
}

/**
 * Simplified world event for analysis
 */
export interface WorldEventSnapshot {
  id: string;
  name: string;
  type: 'crisis' | 'political' | 'economic' | 'social' | 'scandal';
  active: boolean;
  phase: number;
  tags: string[];
  description: string;
}

/**
 * Simplified objective for analysis
 */
export interface ObjectiveSnapshot {
  id: string;
  type: string;
  currentValue: number;
  targetValue: number;
  progress: number; // 0-1
  completed: boolean;
}

/**
 * Simplified actor for analysis
 */
export interface ActorSnapshot {
  id: string;
  name: string;
  category: string;
  trust: number;
  influence: number;
  isRecruited?: boolean;
  suspicionLevel?: number;
}

/**
 * Record of a single action execution
 */
export interface ActionRecord {
  actionId: string;
  phase: number;
  costs: {
    budget?: number;
    capacity?: number;
    risk?: number;
    attention?: number;
    moralWeight?: number;
  };
  effects: {
    trustImpact?: number;
    reachImpact?: number;
    riskImpact?: number;
  };
  success: boolean;
  timestamp: number;
}

/**
 * Historical metrics for trend analysis
 */
export interface MetricsHistory {
  reachHistory: number[]; // Last N phases
  trustHistory: number[]; // Average trust over time
  riskHistory: number[]; // Risk level over time
  budgetHistory: number[]; // Budget over time
}

// ============================================
// ANALYSIS STRATEGY INTERFACE
// ============================================

/**
 * Base interface for NPC analysis strategies
 * Each NPC implements this to generate recommendations
 */
export interface NPCAnalysisStrategy {
  /**
   * Analyze game state and generate recommendations
   * @param context Complete analysis context
   * @returns Array of recommendations (can be empty)
   */
  analyze(context: NPCAnalysisContext): AdvisorRecommendation[];

  /**
   * Optional: Get NPC's name for logging
   */
  getNPCName?(): string;
}

// ============================================
// HELPER TYPES
// ============================================

/**
 * Result of analyzing trends in metrics
 */
export interface TrendAnalysis {
  direction: 'increasing' | 'decreasing' | 'stable';
  rate: number; // Percentage change per phase
  significance: 'high' | 'medium' | 'low';
}

/**
 * Result of ROI (Return on Investment) analysis
 */
export interface ROIAnalysis {
  actionId: string;
  cost: number;
  impact: number;
  roi: number; // Impact per unit cost
  isEfficient: boolean;
}

/**
 * Detected conflict between NPCs
 */
export interface NPCConflict {
  npc1: string;
  npc2: string;
  recommendation1: AdvisorRecommendation;
  recommendation2: AdvisorRecommendation;
  conflictType: 'resource' | 'strategy' | 'priority';
  description: string;
}

// ============================================
// UTILITY FUNCTIONS
// ============================================

/**
 * Generate unique recommendation ID
 */
export function generateRecommendationId(
  npcId: string,
  category: RecommendationCategory
): string {
  return `${npcId}_${category}_${Date.now()}`;
}

/**
 * Check if recommendation is time-sensitive
 */
export function isTimeSensitive(rec: AdvisorRecommendation): boolean {
  return rec.expiresPhase !== undefined;
}

/**
 * Get priority weight for sorting
 */
export function getPriorityWeight(priority: RecommendationPriority): number {
  const weights: Record<RecommendationPriority, number> = {
    critical: 4,
    high: 3,
    medium: 2,
    low: 1,
  };
  return weights[priority];
}

/**
 * Get color for priority level
 */
export function getPriorityColor(priority: RecommendationPriority): string {
  const colors: Record<RecommendationPriority, string> = {
    critical: '#DC2626', // red-600
    high: '#F59E0B', // amber-500
    medium: '#10B981', // green-500
    low: '#6B7280', // gray-500
  };
  return colors[priority];
}

/**
 * Get emoji indicator for priority
 */
export function getPriorityEmoji(priority: RecommendationPriority): string {
  const emojis: Record<RecommendationPriority, string> = {
    critical: '🔴',
    high: '🟡',
    medium: '🟢',
    low: '⚪',
  };
  return emojis[priority];
}

/**
 * Get category label in German
 */
export function getCategoryLabel(category: RecommendationCategory): string {
  const labels: Record<RecommendationCategory, string> = {
    opportunity: 'GELEGENHEIT',
    threat: 'GEFAHR',
    efficiency: 'EFFIZIENZ',
    strategy: 'STRATEGIE',
  };
  return labels[category];
}
